# 该文件仅在开发环境生效, 由文件命名决定
# 位置无所谓,只要在resources里面就行
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B9
    username: root
    password: 970601
  jpa:
    properties:
      hibernate:
        show_sql: true # 在Log中显示SQL语句
        format_sql: true # 竖着打印更加清楚
  # Redis相关配置
  redis:
    localhost: localhost
    port: 6379
    database: 7 # 单独指定一个数据库专门用来归还库存操作, 貌似没生效
    password:
    listen-pattern: __keyevent@0__:expired # psubscribe

# 开发环境用的JWT算法生成相关
missyou:
  security:
    jwt-key: 7777777yue
    token-expired-in: 86400000 #令牌过期时间
  order:
    max-sku-limit: 777 #最大购买数量
    pay-time-limit: 3600

